[package]
name = "doiTAG"
version = "0.7.0"
edition = "2024"
license = "MIT"
authors = ["Gaurav Sablok"]
description = "doiTAG for sequence DOIs"
homepage = "https://codeberg.org/gsablok/doiTAG"
repository = "https://codeberg.org/gsablok/doiTAG"
keywords = ["bioinformatics","genomics"]

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
figlet-rs = "0.1.5"
rayon = "1.11.0"
tokio = { version = "1.47.1", features = ["full"] }
